[2020-05-26 00:57:29,935][<concurrent.futures.thread.ThreadPoolExecutor object at 0x1131e23c8>_0:123145533394944][task_id:django.request][log.py:228][ERROR][Internal Server Error: /customer/poll]
Traceback (most recent call last):
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/wmc/vscode/django/django-air/customer/views.py", line 172, in poll
    pause(room_id, phone_num)
  File "/Users/wmc/vscode/django/django-air/master/mainMachine.py", line 318, in pause
    machine.new_request(room_id=s.room_id, phone_num=phone_num, req_time=int(time.time()), sp_mode=s.sp_mode)
AttributeError: 'NoneType' object has no attribute 'room_id'
[2020-05-26 00:57:29,938][django-main-thread:123145522884608][task_id:django.channels.server][runserver.py:154][ERROR][[35;1mHTTP POST /customer/poll 500 [0.03, 127.0.0.1:51636][0m]
[2020-05-26 00:57:31,973][<concurrent.futures.thread.ThreadPoolExecutor object at 0x1131e23c8>_1:123145538650112][task_id:django.request][log.py:228][ERROR][Internal Server Error: /customer/poll]
Traceback (most recent call last):
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/wmc/vscode/django/django-air/customer/views.py", line 172, in poll
    pause(room_id, phone_num)
  File "/Users/wmc/vscode/django/django-air/master/mainMachine.py", line 318, in pause
    machine.new_request(room_id=s.room_id, phone_num=phone_num, req_time=int(time.time()), sp_mode=s.sp_mode)
AttributeError: 'NoneType' object has no attribute 'room_id'
[2020-05-26 00:57:31,978][django-main-thread:123145522884608][task_id:django.channels.server][runserver.py:154][ERROR][[35;1mHTTP POST /customer/poll 500 [0.04, 127.0.0.1:51636][0m]
[2020-05-26 00:57:32,029][<concurrent.futures.thread.ThreadPoolExecutor object at 0x1131e23c8>_0:123145533394944][task_id:django.request][log.py:228][ERROR][Internal Server Error: /customer/poll]
Traceback (most recent call last):
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/wmc/vscode/django/django-air/customer/views.py", line 172, in poll
    pause(room_id, phone_num)
  File "/Users/wmc/vscode/django/django-air/master/mainMachine.py", line 318, in pause
    machine.new_request(room_id=s.room_id, phone_num=phone_num, req_time=int(time.time()), sp_mode=s.sp_mode)
AttributeError: 'NoneType' object has no attribute 'room_id'
[2020-05-26 00:57:32,036][django-main-thread:123145522884608][task_id:django.channels.server][runserver.py:154][ERROR][[35;1mHTTP POST /customer/poll 500 [0.04, 127.0.0.1:51636][0m]
[2020-05-26 00:57:34,832][<concurrent.futures.thread.ThreadPoolExecutor object at 0x1131e23c8>_1:123145538650112][task_id:django.request][log.py:228][ERROR][Internal Server Error: /customer/poll]
Traceback (most recent call last):
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/wmc/vscode/django/django-air/customer/views.py", line 172, in poll
    pause(room_id, phone_num)
  File "/Users/wmc/vscode/django/django-air/master/mainMachine.py", line 318, in pause
    machine.new_request(room_id=s.room_id, phone_num=phone_num, req_time=int(time.time()), sp_mode=s.sp_mode)
AttributeError: 'NoneType' object has no attribute 'room_id'
[2020-05-26 00:57:34,835][django-main-thread:123145522884608][task_id:django.channels.server][runserver.py:154][ERROR][[35;1mHTTP POST /customer/poll 500 [0.02, 127.0.0.1:51636][0m]
[2020-05-26 00:57:34,856][<concurrent.futures.thread.ThreadPoolExecutor object at 0x1131e23c8>_2:123145543905280][task_id:django.request][log.py:228][ERROR][Internal Server Error: /customer/poll]
Traceback (most recent call last):
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wmc/opt/anaconda3/envs/django/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/wmc/vscode/django/django-air/customer/views.py", line 172, in poll
    pause(room_id, phone_num)
  File "/Users/wmc/vscode/django/django-air/master/mainMachine.py", line 318, in pause
    machine.new_request(room_id=s.room_id, phone_num=phone_num, req_time=int(time.time()), sp_mode=s.sp_mode)
AttributeError: 'NoneType' object has no attribute 'room_id'
[2020-05-26 00:57:34,861][django-main-thread:123145522884608][task_id:django.channels.server][runserver.py:154][ERROR][[35;1mHTTP POST /customer/poll 500 [0.02, 127.0.0.1:51636][0m]
